[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd .. && npm ci",
  "npm ci"
]

[phases.build]
cmds = [
  "cd .. && npm run build",
  "mkdir -p public",
  "cp -r ../dist/. public/"
]

[start]
cmd = "node server.js"
